include sources/driver/mpu6050/Makefile
include sources/driver/hmc5883l/Makefile
include sources/driver/stm32_rtc/Makefile
include sources/driver/sh1106/Makefile
include sources/driver/button/Makefile

