CFLAGS		+= -I./sources/device/core
CPPFLAGS	+= -I./sources/device/core

VPATH += sources/device/core

SOURCES_ASM = sources/device/core/startup_stm32f10x_md.s

LDFILE = sources/device/core/STM32F103RBT6.ld

SOURCES += sources/device/core/system_stm32f10x.c
# SOURCES += sources/device/core/core_cm3.c