
CFLAGS		+= -I./sources/application/Pages
CPPFLAGS	+= -I./sources/application/Pages

VPATH += sources/application/Pages

SOURCES_CPP += sources/application/Pages/page_watch.cpp
SOURCES_CPP += sources/application/Pages/page_menu.cpp

SOURCES_CPP += sources/application/Pages/page_timer.cpp
SOURCES_CPP += sources/application/Pages/page_setting.cpp
SOURCES_CPP += sources/application/Pages/page_mpu.cpp
SOURCES_CPP += sources/application/Pages/page_compass.cpp
SOURCES_CPP += sources/application/Pages/page_runner_game.cpp
SOURCES_CPP += sources/application/Pages/page_flashing.cpp