
include sources/application/Pages/Makefile
include sources/application/Tasks/Makefile

CFLAGS		+= -I./sources/application
CPPFLAGS	+= -I./sources/application

VPATH += sources/application

SOURCES_CPP += sources/application/main.cpp
